[package]
name = "black-diamond-quantum-ecosystem"
version = "3.0.0"
edition = "2021"
description = "Quantum-Enhanced Black Diamond Trading Ecosystem with 20,000x Performance"
authors = ["Black Diamond Team"]

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
# Core async runtime
tokio = { version = "1.35", features = ["full"] }
tokio-tungstenite = "0.21"

# Web server and HTTP
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Solana blockchain integration
solana-client = "1.17"
solana-sdk = "1.17"
solana-account-decoder = "1.17"
anchor-client = "0.29"
anchor-lang = "0.29"

# Cryptography and security
ed25519-dalek = "2.0"
bs58 = "0.5"
sha2 = "0.10"
rand = "0.8"

# Performance optimization
rayon = "1.8"
dashmap = "5.5"
parking_lot = "0.12"
crossbeam = "0.8"

# Quantum-inspired mathematical operations
num-complex = "0.4"
nalgebra = "0.32"
ndarray = "0.15"

# Financial calculations
rust_decimal = "1.33"
bigdecimal = "0.4"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"

# Command line interface
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"

[profile.release]
# Quantum-level optimizations
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# SIMD and CPU-specific optimizations
[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx2,+fma"]

[profile.dev]
opt-level = 1
overflow-checks = true

[features]
default = ["quantum-enhancement"]
quantum-enhancement = []
production = ["quantum-enhancement"]